# Generated by Django 4.2.7 on 2023-11-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PillProperties',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pills.pill')),
                ('custom_shape', models.CharField(max_length=255, null=True)),
                ('shape', models.CharField(max_length=255, null=True)),
                ('color1', models.CharField(max_length=255, null=True)),
                ('color2', models.CharField(max_length=255, null=True)),
                ('print_front', models.CharField(max_length=255, null=True)),
                ('print_back', models.CharField(max_length=255, null=True)),
                ('line_front', models.CharField(max_length=255, null=True)),
                ('line_back', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
