# Generated by Django 4.2.7 on 2023-11-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pill',
            old_name='password',
            new_name='name',
        ),
    ]
