# Generated by Django 4.2.7 on 2023-11-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0003_alter_instructions_pill_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=255)),
                ('clinical_effect', models.CharField(max_length=255)),
                ('mechanism', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
            ],
        ),
    ]
