# Generated by Django 4.2.7 on 2023-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0004_interactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PillComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_name', models.CharField(max_length=255)),
                ('pill_component', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='interactions',
            old_name='name1',
            new_name='component_name1',
        ),
        migrations.RenameField(
            model_name='interactions',
            old_name='name2',
            new_name='component_name2',
        ),
    ]
