# Generated by Django 4.2.7 on 2023-11-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_link', models.CharField(max_length=255)),
                ('label_forms', models.CharField(blank=True, max_length=255)),
                ('label_shapes', models.CharField(blank=True, max_length=255)),
                ('label_color1', models.CharField(blank=True, max_length=255)),
                ('label_color2', models.CharField(blank=True, max_length=255)),
                ('label_line_front', models.CharField(blank=True, max_length=255)),
                ('label_line_back', models.CharField(blank=True, max_length=255)),
                ('label_print_front', models.CharField(blank=True, max_length=255)),
                ('label_print_back', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
