# Generated by Django 4.2.7 on 2023-11-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0002_intructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intructions',
            new_name='Instructions',
        ),
    ]
