# Generated by Django 4.2.7 on 2023-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill', '0005_pillcomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactions',
            name='pill_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
