# Generated by Django 4.2.7 on 2023-11-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_taking_is_taken_remove_taking_scheduled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takingschedule',
            name='is_taken',
        ),
        migrations.AlterField(
            model_name='takingschedule',
            name='scheduled_time',
            field=models.CharField(max_length=255),
        ),
    ]
